# Generated by Django 4.2.2 on 2023-06-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=150)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=50)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('stock', models.IntegerField(default=0)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
